name: Java CI Final con H2 y JDK21

on:
  push:
    branches: [ "master", "unidad-2" ]
  pull_request:
    branches: [ "master", "unidad-2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Configurar Java 21 (Entorno estable)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 3. Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: 3.1 Corregir permisos (Para los dos microservicios)
        run: |
          chmod +x estudiante-service/gradlew
          chmod +x semillero-service/gradlew

      - name: 4. Ejecutar Pruebas - Microservicio Estudiantes
        run: |
          cd estudiante-service
          ./gradlew test

      - name: 5. Ejecutar Pruebas - Microservicio Semilleros
        run: |
          cd semillero-service
          ./gradlew test